-- Migrate the custom auth tables (UserAuthenticated / UserGuest / UserSession)
-- onto BetterAuth's model (User + Session + Account + Verification).
--
-- This migration is data-preserving: existing users, their credentials, profile
-- details and quizzes are carried over. It must NOT be regenerated by
-- `prisma migrate dev` (which would produce a destructive version).

-- 1. Add the new auth columns to User. `email` is nullable for now so existing
--    rows can be backfilled before the NOT NULL + UNIQUE constraints are added.
ALTER TABLE "User"
  ADD COLUMN "name" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "email" TEXT,
  ADD COLUMN "emailVerified" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "image" TEXT,
  ADD COLUMN "isAnonymous" BOOLEAN NOT NULL DEFAULT false;

-- 2. Backfill name/email/emailVerified from the legacy UserAuthenticated rows.
UPDATE "User" u
SET "name" = ua."name",
    "email" = ua."email",
    "emailVerified" = ua."emailVerified"
FROM "UserAuthenticated" ua
WHERE ua."userId" = u."id";

-- 3. Flag guests as anonymous and synthesize an email (BetterAuth requires a
--    non-null, unique email on every user).
UPDATE "User" u
SET "isAnonymous" = true
FROM "UserGuest" g
WHERE g."userId" = u."id";

UPDATE "User"
SET "email" = 'guest-' || "id" || '@guest.local'
WHERE "email" IS NULL AND "isAnonymous" = true;

-- Any remaining user with no email (data anomaly) gets a placeholder so the
-- NOT NULL constraint below can be applied.
UPDATE "User"
SET "email" = 'user-' || "id" || '@unknown.local'
WHERE "email" IS NULL;

-- 4. Create the BetterAuth tables.
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "token" TEXT NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "userId" TEXT NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Account" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "accountId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "accessToken" TEXT,
    "refreshToken" TEXT,
    "idToken" TEXT,
    "accessTokenExpiresAt" TIMESTAMP(3),
    "refreshTokenExpiresAt" TIMESTAMP(3),
    "scope" TEXT,
    "password" TEXT,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Verification" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Verification_pkey" PRIMARY KEY ("id")
);

-- 5. Migrate each legacy credential into an Account row (providerId='credential').
--    The Argon2 hash moves to Account.password; the app's auth config verifies it.
INSERT INTO "Account" ("id", "createdAt", "updatedAt", "accountId", "providerId", "userId", "password")
SELECT gen_random_uuid(), now(), now(), ua."userId", 'credential', ua."userId", ua."hashedPassword"
FROM "UserAuthenticated" ua;

-- 6. Re-point UserDetail from UserAuthenticated.id to the underlying User.id.
ALTER TABLE "UserDetail" DROP CONSTRAINT "UserDetail_userId_fkey";

UPDATE "UserDetail" d
SET "userId" = ua."userId"
FROM "UserAuthenticated" ua
WHERE d."userId" = ua."id";

-- 7. Drop the legacy auth tables and their constraints.
ALTER TABLE "UserAuthenticated" DROP CONSTRAINT "UserAuthenticated_userId_fkey";
ALTER TABLE "UserGuest" DROP CONSTRAINT "UserGuest_userId_fkey";
ALTER TABLE "UserSession" DROP CONSTRAINT "UserSession_userId_fkey";
DROP TABLE "UserSession";
DROP TABLE "UserGuest";
DROP TABLE "UserAuthenticated";

-- 8. Finalize User.email constraints and drop the legacy role column.
ALTER TABLE "User" ALTER COLUMN "email" SET NOT NULL;
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
ALTER TABLE "User" DROP COLUMN "role";

-- 9. Indexes and foreign keys for the new tables.
CREATE UNIQUE INDEX "Session_token_key" ON "Session"("token");
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE INDEX "Account_userId_idx" ON "Account"("userId");
CREATE INDEX "Verification_identifier_idx" ON "Verification"("identifier");

ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserDetail" ADD CONSTRAINT "UserDetail_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
